### ISSUE TITLE
Can I execute the bob spear experiment pipelines on files staying in a remote server? 

### ISSUE THREAD

**Issue by sun8608** [bioidiap/bob.bio.spear#2]
As it states, I apologize if it's not the right place to ask this question. But I think I need to run experiments on files which must stay on the remote server, and meanwhile the problem is bob spear packages cannot be installed on that server.

**Comment by laurentes** [comment]
Hello,

What do you mean exactly by running experiments?
1. Comparing a test sample against a reference sample?
2. Training a complete speaker recognition model?
...

How is the machine 'running experiments' communicating with the remote server? In a sense, you need the data to process them to either take a decision or train a model, right?

If it is just the data access which is different (e.g. you have to perform a query to the remote server to get the data instead of reading the data directly from a regular file system), then yes this is possible but you have to implement this data accessor (you may [or may not] have to update internal functions of spear).

For this kind of question you may rather use the mailing list (https://groups.google.com/forum/#!forum/bob-devel), since this is not an issue with the library but more an open discussion. Keep in mind that we provide open source code and free support (whenever we can and are able to) to use the library. But we (or rather I) won't offer free consulting on how to deploy a specific system using this library for a commercial product.

I'm closing this 'issue' for now. Feel free to continue the discussion on the mailing list.

Kind regards,
