### ISSUE TITLE
Mobio database is missing zt-norm

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.bio.spear#8]
I tried running some experiments with `mobio-audio-male` with the `--zt-norm` option in `verify_gmm.py` but I realized the database does not support ZT normalization. Is there a reason for that?

**Comment by laurentes** [comment]
Hello,

ZT-norm has been implemented in Mobio long time back for the face modality.
It seems that Spear has its own filelist protocols for Mobio within the
package, but without ZT-norm lists as you've noticed..

As far as I remember, the main difference between the face and the speech
version of the database is that for the face modality, five frames were
extracted per video, while for the audio modality you have a single speech
utterance per video. So you should be able to generate the missing ZT-norm
lists from the bob.db.mobio package.

Otherwise, it should also be possible to update bob.db.mobio to support
both face and speech if it is not yet the case (I can't remember how we
handled this when the bi-modal authentication journal paper on Mobio was
written).

Cheers,
Laurent

**Comment by tiagofrepereira2012** [comment]
Well,

The usage of the mobio database on spear looks a little bit unorthodox.
I don't understand why mobio is defined as a file list database here since we have the mobio package (bob.db.mobio).

Does anyone know?

**Comment by 183amir** [comment]
I can see some files named `for_tnorm` and `for_znorm` here: <https://github.com/bioidiap/bob.bio.spear/tree/master/bob/bio/spear/config/database/mobio/mobile0-male/dev>

**Comment by tiagofrepereira2012** [comment]
Ah Laurent was fast on that one :-P

**Comment by laurentes** [comment]
I'm always very alert and 2.30am ;-).

**Comment by 183amir** [comment]
Is this problem happening because mobio database is defined as `DatabaseBob` here and not `DatabaseBobZT`? or should something extra needs to be done?

**Comment by laurentes** [comment]
Oh, yes, you're right. I incorrectly thought the ZT files where in the
norm/ directory.
The wrong class is indeed used in the database configuration file, just try
to change this.

**Comment by 183amir** [comment]
After some checks on the Mobio Database, Tiago and I think that we can safely use `bob.db.mobio` interface in `bob.bio.spear` too. I am going to create a patch to fix this. @khoury or @laurentes Do you see any problem with this approach?

**Comment by laurentes** [comment]
As mentioned above, this should work fine. I haven' t look at the changes
though. L
